Django/Lesson_Five/user_auth/base_app/urls.py
from django.urls import path
from . import views

app_name = 'base_app'

urlpatterns = [
    path('', views.index, name='home'),
    path('signup', views.sign_up, name='sign_up')
]

Django/Lesson_Five/user_auth/user_auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('base_app.urls')),
    path('admin/', admin.site.urls),
]

Django/Lesson_Five/user_auth/base_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission

# Create your models here.

class User(AbstractUser):
    """Extension of User model to add extra profile info"""

    email = models.EmailField(unique=True)

    groups = models.ManyToManyField(Group, related_name='base_app_users', blank=True)
    user_permissions = models.ManyToManyField(Permission,
                                              related_name='base_app_users',
                                              verbose_name=('user permissions'),
                                              blank=True,
                                              help_text=('Specific permissions for this user.'),)

    portfolio_link = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',
                                    # The upload_to is used to specify the directory which you want to save
                                    # the profile pics to in your media folder
                                    # so in the case, it would be 'media/profile_pics
                                    blank=True)
    class Meta:
        app_label = 'base_app'

    def __str__(self) -> str:
        return self.username

Django/Lesson_Five/user_auth/base_app/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):
    """form foe the user"""

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'profile_pic', 'portfolio_link')

Django/Lesson_Five/user_auth/base_app/views.py
from django.shortcuts import render
from .forms import UserForm

# Create your views here.

def index(request):
    """home page"""
    return render(request, "base_app/index.html")

def sign_up(request):
    """user sign up"""

    
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)

            if 'profile_pic' in request.FILES:
                user.profile_pic = request.FILES['profile_pic']
            user.save()            
        else:
            print(user_form.errors)
            return render(request, "base_app/sign_up.html",
                  {'user':user_form,})
    user_form = UserForm()
    return render(request, "base_app/sign_up.html",
                  {'user':user_form,})

Django/Lesson_Five/user_auth/templates/base_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1><em>Welcome To User Authentication!!!</em></h1>
    <a href="{% url 'base_app:sign_up' %}">Sign Up</a>
</body>
</html>

Django/Lesson_Five/user_auth/templates/base_app/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {{ user.as_p }}
        {% csrf_token %}

        <input type="submit"/>
    </form>
    <a href="{% url 'base_app:home' %}">Back</a>
</body>
</html>